[Interface]
# Key for ag-download
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 0K2aVEMMcc3tulJHFg8T6V7NAvykbSzplMn1xmOJLmM=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CA-FREE#4
PublicKey = Y46WhKEXcCGgPn+LXHDrlD93hgVzrA2mju7XQBbyyXU=
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = 149.88.97.97:51820